apiVersion: v1
kind: Service
metadata:
  name: pqc-service
spec:
  type: NodePort
  selector:
    app: pqc-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 4433
      nodePort: 30443
